/*本番用*/

-- CREATE DATABASE IF NOT EXISTS auth_db;
-- CREATE DATABASE IF NOT EXISTS item_db;
/*テスト用*/

DROP DATABASE IF EXISTS auth_db;
DROP DATABASE IF EXISTS equipment_db;
CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS equipment_db;
